# (PART) Overview by species {#p:species .unnumbered}

```{r species-helper}
plot_month_total <- function(x, max_y) {
  plot_ly(
    data  = x, x = ~year, y = ~observed, type = "bar", name = "observed",
    color = I(inbo_palette(2)[1]), hoverinfo = "text",
    text = ~sprintf("observed in %s %i: %s", month, year, observed),
    showlegend = x$month[1] == "January"
  ) |>
  add_markers(
    y = ~estimate, name = "augmented", color = I(inbo_palette(2)[2]),
    text = ~sprintf("augmented in %s %i: %s", month, year, publication),
    showlegend = x$month[1] == "January",
    error_y = list(
      array = ~upper_confidence_limit - estimate,
      arrayminus = ~estimate - lower_confidence_limit
    )
  ) |>
  layout(
    hovermode = "x unified",
    xaxis = list(title = list(font = list(size = 0))),
    yaxis = list(title = list(font = list(size = 0)), range = c(0, max_y))
  ) |>
  add_annotations(
    text = x$month[1], x = 0.5, y = 1.05, xref = "paper", yref = "paper",
    xanchor = "middle", yanchor = "top", showarrow = FALSE
  )
}
```

```{r species-display, results = "asis"}
metadata |>
  distinct(
    .data$species_group_id, .data$location_group_id, .data$species,
    .data$locationgroup
  ) |>
# semi_join(imputed, by = "species_group_id") |>
# # filter(.data$locationgroup %in% c("Vlaanderen", "Vogelrichtlijngebied")) |>
filter(
  .data$locationgroup %in% c(
    "Vlaanderen", #"Estuarien", #"Zeeschelde",
    "Linkeroever"
  )
) |>
# tail(-100) |>
# head(100) |>
  arrange(.data$species, .data$locationgroup) |>
  mutate(
    chapter = ifelse(
      .data$species == lag(as.character(.data$species), 1, default = ""),
      "",
      sprintf("\n# _%s_\n", .data$species)
    ),
    section = ifelse(
      .data$locationgroup == "Vlaanderen", "",
      sprintf("\n## _%s_ in `%s`\n", .data$species, .data$locationgroup)
    )
  ) |>
  transmute(
    rmd = pmap_chr(
      list(
        this_species = .data$species_group_id, this_ch_title = .data$chapter,
        this_location = .data$location_group_id, this_sec_title = .data$section
      ),
      knit_expand, file = "_species_location.Rmd"
    )
  ) -> rmd
knit(text = paste(rmd$rmd, collapse = "\n\n"), quiet = TRUE) |>
  cat()
```
