{{this_ch_title}}

```{r loc-{{this_location}}-setup}
if (interactive()) {
  imputed |>
    slice_sample(n = 1) |>
    semi_join(x = trend, by = c("locationgroup")) -> this_trend
} else {
  trend |>
    filter(
      .data$location_group_id == "{{this_location}}"
    ) -> this_trend
}
this_trend |>
  group_by(.data$duration) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() -> this_trend
average |>
  semi_join(this_trend, by = "locationgroup") |>
  group_by(.data$species, .data$duration) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  arrange(desc(.data$estimate)) -> this_average
```

```{r tbl-trend-{{this_location}}-10}
this_trend |>
  filter(.data$duration == 10) |>
  arrange(desc(.data$estimate)) |>
  select(
    "species", "period", "yearly trend" = "yearly_trend",
    "trend over period" = "period_trend", "classification"
  ) |>
  kable(
    caption = sprintf(
      "Trends over the most recent 10-year period in `%s`",
      this_trend$locationgroup[1]
    )
  )
```

```{r tbl-trend-{{this_location}}-12}
this_trend |>
  filter(.data$duration == 12) |>
  arrange(desc(.data$estimate)) |>
  select(
    "species", "period", "yearly trend" = "yearly_trend",
    "trend over period" = "period_trend", "classification"
  ) |>
  kable(
    caption = sprintf(
      "Trends over the most recent 12-year period in `%s`",
      this_trend$locationgroup[1]
    )
  )
```

```{r tbl-trend-{{this_location}}-max}
this_trend |>
  filter(.data$duration == max(.data$duration)) |>
  arrange(desc(.data$estimate)) |>
  select(
    "species", "period", "yearly trend" = "yearly_trend",
    "trend over period" = "period_trend", "classification"
  ) |>
  kable(
    caption = sprintf(
      "Trends over the full period in `%s`", this_trend$locationgroup[1]
    )
  )
```

```{r}
this_average |>
  filter(.data$duration == 5) |>
  arrange(desc(.data$estimate)) |>
  select(
    "species", "period", "average" = "publication"
  ) |>
  kable(
    caption = sprintf(
      "Average abundance during the last 5-year period in `%s`", 
      this_trend$locationgroup[1]
    )
  )
```
