---
title: "Standard analysis of wintering waterbirds in Flanders, Belgium"
subtitle: Results for the period 1992-2022
author:
  - name:
      given: "Thierry"
      family: "Onkelinx"
    email: "thierry.onkelinx@inbo.be"
    orcid: "0000-0001-8804-4216"
    affiliation: "Research Institute for Nature and Forest (INBO)"
    corresponding: true
  - name:
      given: "Koen"
      family: "Devos"
    email: "koen.devos@inbo.be"
    orcid: "0000-0001-7265-6349"
    affiliation: "Research Institute for Nature and Forest (INBO)"
reviewer:
  - name:
      given: "Hans"
      family: "Van Calster"
    email: "hans.vancalster@inbo.be"
    orcid: "0000-0001-8595-8426"
    affiliation: "Research Institute for Nature and Forest (INBO)"
lang: en
style: Flanders
floatbarrier: subsubsection
keywords: "wetlands; international waterbird census"
community: "inbo"
publication_type: report
funder: Research Institute for Nature and Forest (INBO)
rightsholder: Research Institute for Nature and Forest (INBO)
bibliography: references.bib
link-citations: TRUE
split_by: section+number
site: bookdown::bookdown_site
params:
  raw_data: "~/n2k/watervogels"
  threshold: !r -log(0.75)
output:
  INBOmd::gitbook: default
# Don't run the format below.
# Only required for RStudio to recognise the project as a bookdown project.
# Hence don't use 'Build all formats'.
  bookdown::dontrun: default
---

# Abstract {.unnumbered}

<!-- description: start -->

To do

<!-- description: end -->

```{r setup, include = FALSE}
library(effectclass)
library(git2rdata)
library(INBOtheme)
library(knitr)
library(plotly)
library(scales)
library(tidyverse)
conflicted::conflicts_prefer(
  dplyr::filter, dplyr::lag, dplyr::pull, plotly::layout
)
opts_chunk$set(
  echo = FALSE, eval = TRUE, cache = FALSE, warning = TRUE,
  error = FALSE, message = TRUE
)
if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "svg", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
```

```{r read-data}
results_repo <- repository()
raw_repo <- repository(params$raw_data)
gbif <- read_vc("inst/results/gbif", root = results_repo)
read_vc("species/species", root = raw_repo) |>
  select("id", species = "name_sc") |>
  inner_join(
    read_vc("species/speciesgroup_species", root = raw_repo),
    by = c("id" = "species")
  ) |>
  transmute(
    species = factor(.data$id, levels = .data$id, labels = .data$species),
    species_group_id = factor(.data$speciesgroup), .data$id
  ) -> speciesgroup
read_vc("location/locationgroup", root = raw_repo) |>
  transmute(
    location_group_id = factor(.data$id),
    locationgroup = factor(.data$id, levels = .data$id, labels = .data$description)
  ) -> locationgroup
read_vc("inst/results/metadata", root = results_repo) |>
  inner_join(speciesgroup, by = "species_group_id") |>
  inner_join(locationgroup, by = "location_group_id") |>
  mutate(
    type = factor(
      .data$model_type,
      levels = c(
        "inla binomial: year * (location + month)",
        "inla zeroinflatednbinomial0: year * (location + month)",
        "inla binomial + zeroinflatednbinomial0: year * (location + month)", 
        "aggregate not imputed: sum ~ year + month",
        "aggregate imputed: sum ~ year + month",
        "yearly imputed index: Total ~ Year + Month",
        "smoothed imputed index: Total ~ Year + Month",
        "aggregate imputed: max ~ year", 
        "yearly imputed index: Total ~ Year", 
        "smoothed imputed index: Total ~ Year"
      ),
      labels = c(
        "imputation model for presence",
        "imputation model for non-zero counts",
        "augmented counts", 
        "observed monthly totals",
        "augmented monthly totals",
        "yearly index of augmented monthly totals",
        "smoothed index of augmented monthly totals",
        "winter maximum", 
        "yearly index of winter maximum", 
        "smoothed index of winter maximum"
      )
    )
  ) -> metadata
metadata |>
  select(
    "analysis", "species", "locationgroup", "species_group_id",
    "location_group_id"
  ) |>
  inner_join(
    read_vc("inst/results/observed_monthly_total", root = results_repo),
    by = "analysis"
  ) |>
  rename(observed = "estimate") -> observed
metadata |>
  select(
    "analysis", "species", "locationgroup", "species_group_id",
    "location_group_id", "id"
  ) |>
  inner_join(
    read_vc("inst/results/imputed_monthly_total", root = results_repo),
    by = "analysis"
  ) |>
  mutate(
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit, 
      ucl = .data$upper_confidence_limit
    )
  ) -> imputed
read_vc("inst/results/average", root = results_repo) |>
  group_by(.data$analysis, .data$duration) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2
    )
  ) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    across(
      c("estimate", "lower_confidence_limit", "upper_confidence_limit"), exp
    ),
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit, 
      ucl = .data$upper_confidence_limit
    ),
    display = sprintf(
    "The average number of animals during the last %i-year period (%s) was %s.",
      .data$duration, .data$period, .data$publication
    )
  ) -> average
read_vc("inst/results/difference", root = results_repo) |>
  group_by(.data$analysis, .data$duration, .data$midstart) |>
  slice_max(.data$midend, n = 1) |>
  group_by(.data$analysis, .data$duration) |>
  slice_min(.data$midend, n = 1) |>
  ungroup() |>
  mutate(
    start = sprintf(
      "%i--%i", .data$midstart - .data$duration / 2,
      .data$midstart + .data$duration / 2
    ),
    end = sprintf(
      "%i--%i", .data$midend - .data$duration / 2,
      .data$midend + .data$duration / 2
    )
  ) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    classification = classification(
      lcl = .data$lower_confidence_limit, ucl = .data$upper_confidence_limit,
      threshold = params$threshold
    ),
    across(
      c("estimate", "lower_confidence_limit", "upper_confidence_limit"), exp
    ),
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit, sign = TRUE,
      ucl = .data$upper_confidence_limit, percent = TRUE, change = TRUE
    ),
    display = sprintf(
    "The average number of animals during the %i year period %s was %s (%s)
    compared to the period %s.",
      .data$duration, .data$end, .data$publication,
      class_labels()[.data$classification], .data$start
    )
  ) -> difference
read_vc("inst/results/wintermax", root = results_repo) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit
    )
  ) -> wintermax
read_vc("inst/results/smoothed_wintermax", root = results_repo) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit
    ),
    sd = log(.data$upper_confidence_limit / .data$estimate) / qnorm(0.975),
  ) -> smoothed_wintermax
read_vc("inst/results/yearly_average", root = results_repo) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    sd = (.data$upper_confidence_limit - .data$estimate) / qnorm(0.975),
    across(
      c("estimate", "lower_confidence_limit", "upper_confidence_limit"), exp
    ),
    publication = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit
    )
  ) -> yearly_average
read_vc("inst/results/yearly_change", root = results_repo) -> yearly_change
yearly_change |>
  mutate(
    old = .data$year, year = .data$reference, reference = .data$old,
    estimate = -.data$estimate,
    old = .data$lower_confidence_limit,
    lower_confidence_limit = -.data$upper_confidence_limit,
    upper_confidence_limit = -.data$old
  ) |>
  select(-"old") |>
  bind_rows(yearly_change) |>
  inner_join(
    metadata |>
      select(
        "analysis", "species", "locationgroup", "species_group_id",
        "location_group_id"
      ),
    by = "analysis"
  ) |>
  mutate(
    sd = (.data$upper_confidence_limit - .data$estimate) / qnorm(0.975),
    publication = format_ci(
      exp(.data$estimate), lcl = exp(.data$lower_confidence_limit), sign = TRUE,
      ucl = exp(.data$upper_confidence_limit), percent = TRUE, change = TRUE
    )
  ) -> yearly_change
metadata |>
  select(
    "analysis", "species", "locationgroup", "species_group_id",
    "location_group_id"
  ) |>
  inner_join(
    read_vc("inst/results/trend", root = results_repo), by = "analysis"
  ) |>
  mutate(
    sd = (.data$upper_confidence_limit - .data$estimate) / qnorm(0.975),
    classification = classification(
      .data$lower_confidence_limit, .data$upper_confidence_limit,
      threshold = params$threshold
    ),
    yearly_trend = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit, change = TRUE,
      ucl = .data$upper_confidence_limit, link = "log", percent = TRUE
    ),
    period_trend = format_ci(
      .data$duration * .data$estimate, percent = TRUE,
      lcl = .data$duration * .data$lower_confidence_limit, change = TRUE,
      ucl = .data$duration * .data$upper_confidence_limit, link = "log"
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) -> trend
```

\mainmatter
