---
title: "_{{this_location_name}}_"
---

```{r setup}
library(effectclass)
library(git2rdata)
library(kableExtra)
library(knitr)
library(tidyverse)
opts_chunk$set(echo = FALSE)
conflicted::conflicts_prefer(dplyr::filter, dplyr::pull)
if (interactive()) {
  root <- "../results"
  read_vc("yearly_trend", root = root) |>
    slice_sample(n = 1) |>
    pull(.data$location_group_id) -> this_location
  location_file <- "vlaanderen"
} else {
  this_location <- {{this_location}}
  tolower("{{this_location_name}}") |>
    gsub(pattern = " ", replacement = "-") -> location_file
  root <- "../../results"
}
threshold <- log(0.75)
```

```{r read-species}
read_vc("speciesgroup_species", root) |>
  inner_join(read_vc("species", root), by = c("species" = "id")) |>
  transmute(
    species_group_id = as.character(.data$speciesgroup),
    species = .data$name_sc,
    url = tolower(.data$name_sc) |>
      gsub(pattern = " ", replacement = "-") |>
      sprintf(fmt = "../%1$s/%2$s.html", location_file)
  ) -> species
```

## Augmented monthly totals

### Trends in augmented monthly totals

```{r tbl-yearly-trend-10}
#| tbl-cap: "Linear change in augmented monthly total over the most recent
#|   10-year period in `{{this_location_name}}`."
read_vc("yearly_trend", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "yearly change", "change over period"
  ) |>
  kable(align = "lrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    3:4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

```{r tbl-yearly-trend-12}
#| tbl-cap: "Linear change in augmented monthly total over the most recent
#|   12-year period in `{{this_location_name}}`."
read_vc("yearly_trend", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 12
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "yearly change", "change over period"
  ) |>
  kable(align = "lrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    3:4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

```{r tbl-yearly-trend-max}
#| tbl-cap: "Linear change in augmented monthly total over the entire time
#|   series in `{{this_location_name}}`."
read_vc("yearly_trend", root) |>
  filter(.data$location_group_id == this_location) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$duration, n = 1) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "duration", "yearly change", "change over period"
  ) |>
  kable(align = "lrrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    4:5, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

### Long-term average of augmented monthly totals

```{r tbl-yearly-average-5}
#| tbl-cap: "Average augmented montly total over most recent 5-year period in
#|   `{{this_location_name}}`."
read_vc("yearly_average", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 5
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  inner_join(species, by = "species_group_id") |>
  arrange(desc(.data$estimate)) |>
  mutate(
    .data$species,
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    ),
    average = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log"
    )
  ) -> average
average |>
  select("species", "period", "average") |>
  kable(align = "lcc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = average$url)
```

```{r tbl-yearly-average-10}
#| tbl-cap: "Average augmented montly total over most recent 10-year period in
#|   `{{this_location_name}}`."
read_vc("yearly_average", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  inner_join(species, by = "species_group_id") |>
  arrange(desc(.data$estimate)) |>
  mutate(
    .data$species,
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    ),
    average = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log"
    )
  ) -> average
average |>
  select("species", "period", "average") |>
  kable(align = "lcc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = average$url)
```

### Change in long-term average of augmented monthly totals

```{r tbl-yearly-change-10}
#| tbl-cap: "Change in average augmented monthly total between the most recent
#|   10-year period compared to the oldest 10-year period in
#|   `{{this_location_name}}`."
read_vc("yearly_difference", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midend, n = 1) |>
  slice_min(.data$midstart, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    change = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    from = paste(
      .data$midstart - .data$duration / 2 - 1,
      .data$midstart + .data$duration / 2, sep = "--"
    ),
    to = paste(
      .data$midend - .data$duration / 2 - 1,
      .data$midend + .data$duration / 2, sep = "--"
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "from", "to", "change"
  ) |>
  kable(align = "lrrc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

## Winter maximum

### Trends in winter maxima

```{r tbl-wintermax-trend-10}
#| tbl-cap: "Linear change in winter maximum over the most recent
#|   10-year period in `{{this_location_name}}`."
read_vc("wintermax_trend", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "yearly change", "change over period"
  ) |>
  kable(align = "lrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    3:4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

```{r tbl-wintermax-trend-12}
#| tbl-cap: "Linear change in winter maximum over the most recent
#|   12-year period in `{{this_location_name}}`."
read_vc("wintermax_trend", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 12
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "yearly change", "change over period"
  ) |>
  kable(align = "lrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    3:4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

```{r tbl-wintermax-trend-max}
#| tbl-cap: "Linear change in winter maximum over the entire time
#|   series in `{{this_location_name}}`."
read_vc("wintermax_trend", root) |>
  filter(.data$location_group_id == this_location) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$duration, n = 1) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    `yearly change` = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    `change over period` = format_ci(
      .data$estimate * .data$duration, change = TRUE, link = "log",
      lcl = .data$lower_confidence_limit * .data$duration,
      ucl = .data$upper_confidence_limit * .data$duration, percent = TRUE
    ),
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "period", "duration", "yearly change", "change over period"
  ) |>
  kable(align = "lrrccc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    4:5, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

### Long-term average winter maximum

```{r tbl-wintermax-average-5}
#| tbl-cap: "Average winter maximum over most recent 5-year period in
#|   `{{this_location_name}}`."
read_vc("wintermax_average", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 5
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  inner_join(species, by = "species_group_id") |>
  arrange(desc(.data$estimate)) |>
  mutate(
    .data$species,
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    ),
    average = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log"
    )
  ) -> average
average |>
  select("species", "period", "average") |>
  kable(align = "lcc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = average$url)
```

```{r tbl-wintermax-average-10}
#| tbl-cap: "Average winter maximum over most recent 10-year period in
#|   `{{this_location_name}}`."
read_vc("wintermax_average", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midyear, n = 1) |>
  ungroup() |>
  inner_join(species, by = "species_group_id") |>
  arrange(desc(.data$estimate)) |>
  mutate(
    .data$species,
    period = sprintf(
      "%.0f--%.0f", .data$midyear - .data$duration / 2 + 0.5,
      .data$midyear + .data$duration / 2 - 0.5
    ),
    average = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log"
    )
  ) -> average
average |>
  select("species", "period", "average") |>
  kable(align = "lcc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = average$url)
```

### Change in long-term average winter maximum

```{r tbl-wintermax-change-10}
#| tbl-cap: "Change in average winter maximum between the most recent
#|   10-year period compared to the oldest 10-year period in
#|   `{{this_location_name}}`."
read_vc("wintermax_difference", root) |>
  filter(
    .data$location_group_id == this_location,
    .data$duration == 10
  ) |>
  group_by(.data$species_group_id) |>
  slice_max(.data$midend, n = 1) |>
  slice_min(.data$midstart, n = 1) |>
  ungroup() |>
  mutate(
    classification = classification(
      lcl = .data$duration * .data$lower_confidence_limit, 
      ucl = .data$duration * .data$upper_confidence_limit,
      threshold = threshold
    ),
    change = format_ci(
      .data$estimate, lcl = .data$lower_confidence_limit,
      ucl = .data$upper_confidence_limit, link = "log", change = TRUE,
      percent = TRUE
    ),
    from = paste(
      .data$midstart - .data$duration / 2 - 1,
      .data$midstart + .data$duration / 2, sep = "--"
    ),
    to = paste(
      .data$midend - .data$duration / 2 - 1,
      .data$midend + .data$duration / 2, sep = "--"
    )
  ) |>
  inner_join(species, by = "species_group_id") |>
  arrange(.data$classification, desc(.data$estimate)) -> trend
trend |>
  select(
    "species", "from", "to", "change"
  ) |>
  kable(align = "lrrc") |>
  kable_paper(
    c("hover", "striped", "responsive"), full_width = FALSE, fixed_thead = TRUE
  ) |>
  column_spec(1, link = trend$url) |>
  column_spec(
    4, color = "white",
    background = effectclass:::detailed_signed_palette[trend$classification]
  )
```

