---
title: "Standard analysis wintering waterbirds in Belgium"
subtitle: "Interactive report"
author: 
  - 
    name: "Thierry Onkelinx"
    email: "thierry.onkelinx@inbo.be"
  - 
    name: "Koen Devos"
    email: "koen.devos@inbo.be"
link-citations: TRUE
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    split_by: "section+number"
    template: !expr INBOmd::inbo_rapport_css("html")
    dpi: 300
    fig.width: 200 / 25.4
    fig.height: 100 / 25.4
---

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, eval = TRUE, cache = FALSE,
  warning = FALSE, error = TRUE, message = TRUE
)
library(tidyverse)
library(plotly)
library(DT)
library(INBOtheme)
theme_set(theme_inbo(base_family = "Flanders Art Sans", base_size = 12))
```

# Introduction

To do

```{r read-results}
readRDS("../rapport/results.Rds") %>%
  mutate(LocationGroup = LocationGroup %>%
           str_replace("België", "Belgium") %>%
           str_replace("Vogelrichtlijn", "SPA")) -> results
split <- grep(" ", results$LocationGroup)
results$LocationGroup[-split] <- paste("Total", results$LocationGroup[-split])
results %>%
  filter(grepl("yearly", ModelType), LocationGroup == "Total Belgium") %>%
  select(SpeciesGroupID, Parameter, Estimate) %>%
  group_by(SpeciesGroupID) %>%
  arrange(desc(Parameter)) %>%
  slice(1) %>%
  ungroup() %>%
  arrange(desc(Estimate)) %>%
  transmute(SpeciesGroupID, Order = row_number()) %>%
  inner_join(results, by = "SpeciesGroupID") -> results
```
