---
title: "Analysis of wintering waterbirds"
author: 
  - 
    name: "Thierry Onkelinx"
    email: "thierry.onkelinx@inbo.be"
  - 
    name: "Koen Devos"
    email: "koen.devos@inbo.be"
subtitle: "Internal validation report"
link-citations: TRUE
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    lot: FALSE
    lof: FALSE
    floatbarrier: subsubsection
    lang: english
    bookdown::gitbook:
    split_by: "chapter+number"
    template: !expr INBOmd::inbo_rapport_css("html")
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
---

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 70 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(tidyverse)
library(scales)
library(INBOtheme)
theme_set(theme_inbo(base_family = "Flanders Art Sans", base_size = 12))
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") != "html") {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(theme_inbo(base_family = "Flanders Art Sans", base_size = 8))
}
```

# Introduction

```{r read-data}
readRDS("../rapport/results.Rds") %>%
  mutate(
    id = LocationGroup %>%
      str_replace("ë", "e") %>%
      abbreviate() %>%
      interaction(abbreviate(scientific_name, 10), sep = "-") %>%
      as.character() %>%
      str_replace_all(" ", "-")
    ) -> results
readRDS("../rapport/location.Rds") -> location
```
