```{r import-locations, eval = !file.exists("location.Rds"), results = "hide", message = FALSE}
library(n2kanalysis)
result_channel <- n2khelper::connect_result(
  username = Sys.getenv("N2KRESULT_USERNAME"),
  password = Sys.getenv("N2KRESULT_PASSWORD")
)
tbl(result_channel, "scheme") %>%
  filter(description == "Watervogels") %>%
  semi_join(x = tbl(result_channel, "location_group"),
            by = c("scheme" = "id")) %>%
  semi_join(x = tbl(result_channel, "location_group_location"),
             by = c("location_group" = "id")) %>%
  semi_join(x = tbl(result_channel, "location"),
             by = c("id" = "location")) %>%
  select(fingerprint, location = description) %>%
  arrange(fingerprint) %>%
  collect() %>%
  saveRDS("location.Rds")
```

```{r import-manifests, eval = !file.exists("manifests.Rds"), results = "hide", message = FALSE}
library(aws.s3)
library(n2kanalysis)
if (file.exists("stored.Rds")) {
  file.remove("stored.Rds") -> junk
}
project <- "watervogels"
aws_base <- get_bucket("n2kmonitoring", prefix = project, max = 1)
local_base <- normalizePath("~/analysis")
file.path(local_base, project, "manifest") %>%
  list.files(full.names = TRUE) %>%
  str_remove(paste0(local_base, "/")) -> local_manifest

get_manifest <- function(hash, local) {
  message(hash, " reading manifest")
  if (local) {
    read_manifest(base = local_base, project = project, hash = hash) %>%
      slot("Manifest") -> x
    return(x)
  }
  x <- read_manifest(base = aws_base, project = project, hash = hash)
  store_manifest(x, base = local_base, project = project)
  return(slot(x, "Manifest"))
}
sprintf("%s/manifest", project) %>%
  get_bucket_df(bucket = aws_base) %>%
  select(Key, LastModified) %>%
  mutate(
    LastModified = as.POSIXct(LastModified, format = "%Y-%m-%dT%H:%M:%S")
  ) %>%
  mutate(
    local = Key %in% local_manifest,
    hash = basename(Key) %>%
      str_remove("\\.manifest"),
    manifest = map2(hash, local, get_manifest)
  ) %>%
  unnest() -> aws_manifest

aws_manifest %>%
  mutate(Level = ifelse(is.na(Parent), 1, NA)) -> aws_manifest
while (any(is.na(aws_manifest$Level))) {
  aws_manifest %>%
    filter(is.na(Level)) %>%
    left_join(
      aws_manifest %>%
        filter(Level == max(Level, na.rm = TRUE)) %>%
        distinct(Parent = Fingerprint, pLevel = Level + 1),
      by = "Parent"
    ) %>%
    select(-Level, Level = pLevel) -> updated
  if (all(is.na(updated$Level))) {
    stop("All NA")
  }
  bind_rows(
    updated,
    aws_manifest %>%
      filter(!is.na(Level))
  ) -> aws_manifest
}

get_species <- function(x) {
  message(x, " getting species group and location group")
  base <- local_base
  y <- try(read_model(x, base = base, project = project))
  if (inherits(y, "try-error")) {
    y <- NULL
  }
  if (is.null(y)) {
    base <- aws_base
    y <- try(read_model(x, base = base, project = project))
    if (inherits(y, "try-error")) {
      y <- NULL
    }
  }
  if (is.null(y)) {
    return(tibble(SpeciesGroupID = NA_character_, 
                  LocationGroupID = NA_character_))
  } 
  y %>%
    slot("AnalysisMetadata") %>%
    select(SpeciesGroupID, LocationGroupID)
}
aws_manifest %>%
  filter(is.na(Parent)) %>%
  arrange(desc(LastModified)) %>%
  group_by(hash) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(meta = map(Fingerprint, get_species))  %>%
  unnest() -> manifest_species_location
manifest_species_location %>%
  filter(is.na(SpeciesGroupID)) %>%
  select(Key, hash, LastModified) %>%
  saveRDS("problem_manifest.Rds")
manifest_species_location %>%
  filter(!is.na(SpeciesGroupID)) %>%
  arrange(desc(LastModified)) %>%
  group_by(SpeciesGroupID, LocationGroupID) %>%
  slice(1) %>%
  select(hash, SpeciesGroupID, LocationGroupID) %>%
  inner_join(x = aws_manifest, by = "hash") %>%
  saveRDS("manifests.Rds")
```

```{r import-data, eval = !file.exists("stored.Rds"), results = "hide", message = FALSE}
library(aws.s3)
library(n2kanalysis)

if (file.exists("results.Rds")) {
  file.remove("results.Rds") -> junk
}

project <- "watervogels"
aws_base <- get_bucket("n2kmonitoring", prefix = project, max = 1)
local_base <- "~/analysis"

result_channel <- n2khelper::connect_result(
  username = Sys.getenv("N2KRESULT_USERNAME"),
  password = Sys.getenv("N2KRESULT_PASSWORD")
)

tbl(result_channel, "scheme") %>%
  filter(description == "Watervogels") %>%
  semi_join(x = tbl(result_channel, "species_group"),
            by = c("scheme" = "id")) %>%
  select(SpeciesGroupID = fingerprint, SpeciesGroup = description, id) %>%
  inner_join(
    tbl(result_channel, "species_group_species") %>%
      filter(is.na(destroy)) %>%
      select(species_group, species),
    by = c("id" = "species_group")
  ) %>%
  left_join(
    tbl(result_channel, "species") %>%
      select(id, scientific_name) %>%
      left_join(
        tbl(result_channel, "species_common_name") %>%
          filter(is.na(destroy)) %>%
          select(id = language, species, common_name = description) %>%
          inner_join(
            tbl(result_channel, "language") %>%
              select(id, language = description),
            by = "id"
          ) %>%
          select(-id),
        by = c("id" = "species")
      ),
    by = c("species" = "id")
  ) %>%
  arrange(SpeciesGroupID) %>%
  select(-id, -species) %>%
  collect() %>%
  spread(language, common_name) %>%
  mutate_at(c("SpeciesGroup", "scientific_name", "Nederlands"), factor) ->
  species_list
saveRDS(species_list, "speciesgroup.Rds")

tbl(result_channel, "scheme") %>%
  filter(description == "Watervogels") %>%
  semi_join(x = tbl(result_channel, "location_group"),
            by = c("scheme" = "id")) %>%
  select(LocationGroupID = fingerprint, LocationGroup = description) %>%
  collect() %>%
  mutate(LocationGroup = str_replace(LocationGroup, "\\\\u0137", "ë") %>%
           factor()) -> location_group
saveRDS(location_group, "locationgroup.Rds")

relevant <- readRDS("manifests.Rds")
relevant %>%
  distinct(hash, LastModified, LocationGroupID, SpeciesGroupID) %>%
  inner_join(species_list, by = "SpeciesGroupID") %>%
  inner_join(location_group, by = "LocationGroupID") %>%
  arrange(desc(LastModified)) %>%
  group_by(SpeciesGroup, LocationGroupID) %>%
  slice(1) %>%
  ungroup() %>%
  semi_join(x = relevant, by = "hash") %>%
  inner_join(species_list, by = "SpeciesGroupID") %>%
  inner_join(location_group, by = "LocationGroupID") %>%
  select(-SpeciesGroupID, -LocationGroupID) -> relevant
saveRDS(relevant, "relevant.Rds")

local_copy <- function(hash, base, local_base, project) {
  file.path(local_base, project, str_trunc(hash, 4, ellipsis = "")) %>%
    list.files(recursive = TRUE) %>%
    str_subset(hash) -> available
  if (length(available)) {
    if (length(available) > 1) {
      stop("duplicates ", hash)
    }
    file.path(project, str_trunc(hash, 4, ellipsis = ""), available) %>%
      get_bucket(bucket = base) -> available.aws
    if (length(available.aws)) {
      message(hash, " no update")
      return(FALSE)
    }
  }
  message(hash, " update")
  x <- try(read_model(hash, base, project))
  if (inherits(x, "try-error")) {
    return(TRUE)
  }
  x <- try(store_model(x, local_base, project, overwrite = TRUE, 
                       validate = FALSE))
  return(inherits(x, "try-error"))
}
relevant %>%
  distinct(Fingerprint) %>%
  arrange(Fingerprint) %>%
  mutate(
    failure = map_lgl(Fingerprint, local_copy, base = aws_base,
                     local_base = local_base, project = project)
  ) %>%
  filter(!failure) %>%
  saveRDS("stored.Rds")
```

```{r extract-result, eval = !file.exists("results.Rds"), results = "hide", message = TRUE}
year_month <- function(z) {
  if (has_name(z, "Month")) {
    sprintf("imputed total: %i-%s", z$Year, z$Month)
  } else {
    sprintf("imputed total: %i-unknown", z$Year)
  }
}

get_monthly_total <- function(x, hash) {
  if (is.null(x@Join)) {
    x@RawImputed@Data %>%
      filter(!Missing) %>%
      mutate(Parameter = sprintf("observed total: %i-%s", Year, Month)) %>%
      group_by(Parameter) %>%
      summarise(Estimate = sum(Count)) -> mt
  } else {
    x@RawImputed@Data %>%
      semi_join(x@Join[[1]], by = "LocationID") %>%
      filter(!Missing) %>%
      mutate(Parameter = sprintf("observed total: %i-%s", Year, Month)) %>%
      group_by(Parameter) %>%
      summarise(Estimate = sum(Count)) -> mt
  }
  mt %>%
    bind_rows(
      tibble(
        Parameter = year_month(x@AggregatedImputed@Covariate),
        Estimate = rowMeans(x@AggregatedImputed@Imputation),
        LCL = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.025),
        UCL = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.975),
        p05 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.05),
        p15 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.15),
        p35 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.35),
        p65 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.65),
        p85 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.85),
        p95 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.95)
      )
    ) %>%
    mutate(FileFingerprint = hash)
}

extract_results_mi <- function(x, hash) {
  x@AnalysisMetadata %>%
  select(SpeciesGroupID, LocationGroupID, ModelType, Duration,
         FileFingerprint, StatusFingerprint, Status) %>%
  inner_join(x@AnalysisRelation, by = c("FileFingerprint" = "Analysis")) ->
    result
  if (x@AnalysisMetadata$Status != "converged") {
    return(result)
  }
  result %>%
    inner_join(
      x@Results %>%
        mutate(
          FileFingerprint = hash,
          Parameter = as.character(Parameter)
        ),
      by = "FileFingerprint"
    )
}

extract_results_ag <- function(x, hash) {
  x@AnalysisMetadata %>%
  select(SpeciesGroupID, LocationGroupID, ModelType, Duration,
         FileFingerprint, StatusFingerprint, Status) %>%
  inner_join(x@AnalysisRelation, by = c("FileFingerprint" = "Analysis")) ->
    result
  if (x@AnalysisMetadata$Status != "converged") {
    return(result)
  }
  switch(
    x@AnalysisMetadata$ModelType,
    "aggregate imputed: max ~ Year" = tibble(
      Parameter = as.character(x@AggregatedImputed@Covariate$Year),
      Estimate = rowMeans(x@AggregatedImputed@Imputation),
      LCL = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.025),
      UCL = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.975),
      p05 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.05),
      p15 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.15),
      p35 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.35),
      p65 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.65),
      p85 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.85),
      p95 = apply(x@AggregatedImputed@Imputation, 1, quantile, 0.95),
      FileFingerprint = hash
    ),
    "aggregate imputed: sum ~ Year + Month" = get_monthly_total(x, hash),
    stop(x@AnalysisMetadaws_manifest, ata$ModelType, " ", hash)
  ) %>%
    inner_join(result, by = "FileFingerprint")
}

extract_results_inla <- function(x, hash) {
  x@AnalysisMetadata %>%
    select(SpeciesGroupID, LocationGroupID, ModelType, Duration,
           FileFingerprint, StatusFingerprint, Status) %>%
    inner_join(x@AnalysisRelation, by = c("FileFingerprint" = "Analysis")) ->
    result
  if (x@AnalysisMetadata$Status != "converged") { 
    return(result)
  }
  estimates <- tibble(Parameter = character(0))
  if (!is.null(x@Model$summary.random$LocationID)) {
    x@Model$summary.random$LocationID %>%
      transmute(Parameter = paste("location:", ID), Estimate = mean, 
                LCL = `0.025quant`, UCL = `0.975quant`, 
                FileFingerprint = hash) %>%
      bind_rows() -> estimates
  }
  if (!is.null(x@RawImputed)) {
    if (!has_name(x@RawImputed@Data, "LocationID")) {
      x@RawImputed@Data %>%
        mutate(LocationID = NA) -> x@RawImputed@Data
    }
    x@RawImputed@Data %>%
      filter(Missing) %>%
      select(LocationID, Year, Month) %>%
      bind_cols(
        data.frame(
          Estimate = apply(x@RawImputed@Imputation, 1, median),
          LCL = apply(x@RawImputed@Imputation, 1, quantile, 0.025),
          UCL = apply(x@RawImputed@Imputation, 1, quantile, 0.975)
        )
      ) -> imputations
    imputations %>%
      group_by(LocationID) %>%
      summarise(n = max(Estimate)) %>%
      top_n(10, n) %>%
      bind_rows(
        x@RawImputed@Data %>%
          filter(is.na(Count)) %>%
          count(LocationID) %>%
          top_n(10, n)
      ) -> selected
    x@RawImputed@Data %>%
      filter(!Missing) %>%
      select(LocationID, Year, Month, Estimate = Count) %>%
      bind_rows(imputations) %>%
      semi_join(selected, by = "LocationID") %>%
      transmute(Parameter = sprintf("imputation: %s:%s:%s", LocationID, 
                                    Year, Month),
                Estimate, LCL, UCL, FileFingerprint = hash) %>%
      bind_rows(estimates) -> estimates
  }
  result %>%
    left_join(estimates, by = "FileFingerprint")
}

extract_results <- function(x, hash, base, project) {
  if (inherits(x, "n2kAggregate")) {
    return(extract_results_ag(x, hash))
  }
  if (inherits(x, "n2kModelImputed")) {
    return(extract_results_mi(x, hash))
  }
  if (inherits(x, "n2kInla")) {
    return(extract_results_inla(x, hash))
  }
  stop(class(x), " not handled ", hash)
}

store_results <- function(hash, base, project) {
  message(hash, appendLF = FALSE)
  target <- file.path(base, project, "result", paste0(hash, ".Rds"))
  x <- try(read_model(hash, base = base, project = project))
  if (inherits(x, "try-error")) {
    tibble(FileFingerprint = hash, Status = "missing") %>%
      saveRDS(target)
    return(NULL)
  }
  if (file.exists(target)) {
    message(" existing", appendLF = FALSE)
    readRDS(target) %>%
      distinct(StatusFingerprint) %>%
      pull(StatusFingerprint) -> status_fingerprint
    if (x@AnalysisMetadata$StatusFingerprint == status_fingerprint) {
      message(" up to date")
      return(NULL)
    }
    message(" update")
  } else {
    message(" new")
  }
  extract_results(x, hash, base, project) %>%
    saveRDS(target)
  return(NULL)
}

library(n2kanalysis)
project <- "watervogels"
local_base <- normalizePath("~/analysis")

file.path(local_base, project, "result") %>%
  dir.create(showWarnings = FALSE)
relevant <- readRDS("relevant.Rds")
relevant %>%
  distinct(Fingerprint) %>%
  arrange(Fingerprint) %>%
  pull(Fingerprint) %>%
  sapply(store_results, base = local_base, project = project) -> junk
file.path(local_base, project, "result") %>%
  list.files(full.names = TRUE) -> prepared_results
file.path(local_base, project, "result") %>%
  sprintf(fmt = "%s/%s.Rds", relevant$Fingerprint) -> required_results
required_results[required_results %in% prepared_results] %>%
  lapply(readRDS) %>%
  bind_rows() %>%
  inner_join(
    relevant %>%
      select(Fingerprint, Key, LastModified), 
    by = c("FileFingerprint" = "Fingerprint")
  ) %>%
  inner_join(readRDS("speciesgroup.Rds"), by = "SpeciesGroupID") %>%
  inner_join(readRDS("locationgroup.Rds"), by = "LocationGroupID") %>%
  saveRDS("results.Rds")
```

```{r read-data}
readRDS("results.Rds") -> results

results %>%
  filter(Status != "error") %>%
  mutate(id = as.character(scientific_name) %>% 
           str_replace_all(" ", "-"),
         LocationGroup = str_replace(LocationGroup, "België", "Belgium") %>%
           str_replace("Vlaanderen", "Flanders") %>%
           str_replace("Wallonië", "Wallonia") %>%
           str_replace("Vogelrichtlijn (.*)", "\\1 SPA"),
         loc_id = LocationGroup %>%
           str_replace_all(" ", "-") %>%
           interaction(id, sep = "-")
         ) -> results
results %>%
  filter(ModelType == "imputed average: Total ~ cPeriod", 
         Parameter == "(Intercept)") %>%
  select(id, LocationGroup, Estimate, LCL, UCL) %>%
  mutate_at(c("Estimate", "LCL", "UCL"), exp) %>%
  mutate(
    Magnitude = floor(log10(UCL)),
    Magnitude = Magnitude - ifelse(UCL < 2 * 10 ^ Magnitude, 1, 0)
  ) %>%
  mutate_at(
    c(pEstimate = "Estimate", pLCL = "LCL", pUCL = "UCL"), 
    function(x, m) {
      round(x / 10 ^ m, 1) * 10 ^ m
    },
    .$Magnitude
  ) %>%
  mutate(
    Detailed = sprintf("%0.1f (%0.1f; %0.1f)", Estimate, LCL, UCL),
    `For publication` = sprintf("%s (%s; %s)", pEstimate, pLCL, pUCL)
  ) %>%
  select(-Magnitude) -> wintermax
```
